### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by bigoper** [TheJaredWilcurt/UGUI#11]
## Test environement
```
OS: MacOS Big Sur
npm --version  7.21.0
node --version v16.8.0
```

## Based on the `quick start`
1. Download latest release of UGUI (1.3.0)
2. Extract the UGUI folder from the zip file
3. `npm install`
4. `npm start`

## Error
```
npm ERR! code 1
npm ERR! path /Users/aviivgi/Documents/development/blitzz.io/ugui/1.3.0/node_modules/nw
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! fs.js:47
npm ERR! } = primordials;
npm ERR!     ^
npm ERR! 
npm ERR! ReferenceError: primordials is not defined
npm ERR!     at fs.js:47:5
npm ERR!     at req_ (/Users/aviivgi/Documents/development/blitzz.io/ugui/1.3.0/node_modules/natives/index.js:143:24)
npm ERR!     at Object.req [as require] (/Users/aviivgi/Documents/development/blitzz.io/ugui/1.3.0/node_modules/natives/index.js:55:10)
npm ERR!     at Object.<anonymous> (/Users/aviivgi/Documents/development/blitzz.io/ugui/1.3.0/node_modules/download/node_modules/graceful-fs/fs.js:1:37)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:94:18)
```

**Comment by bigoper** [comment]
Additional Info
```
gulp --version
CLI version: 2.3.0
```

**Comment by TheJaredWilcurt** [comment]
UGUI is pretty old, and based on a very old version of NW.js. So it only works if you use `nvm` to change your global node version to an older version of Node, like `4.0.0`. You may be off using a newer NW.js boilerplate:

* https://nwutils.io/#boilerplates
